import datetime

def existing_save_logfile(name,quantity,rate,igst,cgst,sgst,taxablevalue,amount,totaltaxablevalue,totalamount):
    t_date=datetime.date.today()
    log_file=open("%s.txt",'a',(name,))
    log_file.write(t_date)
    log_file.write("\n")
    log_file.write("Quantity:")
    log_file.write(quantity)
    log_file.write("\n")
    log_file.write("Price:")
    log_file.write(rate)
    log_file.write("\n")
    log_file.write("IGST:")
    log_file.write(igst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("CGST")
    log_file.write(cgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("SGST")
    log_file.write(sgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("Taxable Value:")
    log_file.write(taxablevalue)
    log_file.write("\n")
    log_file.write("Amount:")
    log_file.write(amount)
    log_file.write("\n")
    log_file.write("\n")
    log_file.write("Total Taxable Value")
    log_file.write(totaltaxablevalue)
    log_file.write("\n")
    log_file.write("Total Amount")
    log_file.write(totalamount)
    log_file.write("\n")
    log_file.write("\n")
    log_file.close()

def new_next_logfile(name,quantity,rate,igst,cgst,sgst,taxablevalue,amount):
    t_date=datetime.date.today()
    log_file=open("%s.txt",'w',(name,))
    log_file.write(t_date)
    log_file.write("\n")
    log_file.write("Quantity:")
    log_file.write(quantity)
    log_file.write("\n")
    log_file.write("Price:")
    log_file.write(rate)
    log_file.write("\n")
    log_file.write("IGST:")
    log_file.write(igst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("CGST")
    log_file.write(cgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("SGST")
    log_file.write(sgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("Taxable Value:")
    log_file.write(taxablevalue)
    log_file.write("\n")
    log_file.write("Amount:")
    log_file.write(amount)
    log_file.write("\n")
    log_file.write("\n")
    log_file.close()

def existing_next_logfile(name,quantity,rate,igst,cgst,sgst,taxablevalue,amount):
    t_date=datetime.date.today()
    log_file=open("%s.txt",'a',(name,))
    log_file.write(t_date)
    log_file.write("\n")
    log_file.write("Quantity:")
    log_file.write(quantity)
    log_file.write("\n")
    log_file.write("Price:")
    log_file.write(rate)
    log_file.write("\n")
    log_file.write("IGST:")
    log_file.write(igst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("CGST")
    log_file.write(cgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("SGST")
    log_file.write(sgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("Taxable Value:")
    log_file.write(taxablevalue)
    log_file.write("\n")
    log_file.write("Amount:")
    log_file.write(amount)
    log_file.write("\n")
    log_file.write("\n")
    log_file.close()

def new_save_logfile(name,quantity,rate,igst,cgst,sgst,taxablevalue,amount,totaltaxablevalue,totalamount):
    t_date=datetime.date.today()
    log_file=open("%s.txt",'w',(name,))
    log_file.write(t_date)
    log_file.write("\n")
    log_file.write("Quantity:")
    log_file.write(quantity)
    log_file.write("\n")
    log_file.write("Price:")
    log_file.write(rate)
    log_file.write("\n")
    log_file.write("IGST:")
    log_file.write(igst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("CGST")
    log_file.write(cgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("SGST")
    log_file.write(sgst)
    log_file.write("%")
    log_file.write("\n")
    log_file.write("Taxable Value:")
    log_file.write(taxablevalue)
    log_file.write("\n")
    log_file.write("Amount:")
    log_file.write(amount)
    log_file.write("\n")
    log_file.write("Total Taxable Value")
    log_file.write(totaltaxablevalue)
    log_file.write("\n")
    log_file.write("Total Amount")
    log_file.write(totalamount)
    log_file.write("\n")
    log_file.write("\n")
    log_file.close()
